### ISSUE TITLE
Crash TaskFetchOriginalImageData on data.append

### ISSUE THREAD

**Issue by lukluca** [kean/Nuke#738]
Hi! 

I just noticed that there is a crash on TaskFetchOriginalImageData.

this is the stack trace

Signal: SIGTRAP
EXC_BREAKPOINT (SIGTRAP): EXC_BREAKPOINT (SIGTRAP)

libswiftCore.dylib
_assertionFailure(_:_:file:line:flags:) + 248
libswiftCore.dylib
_assertionFailure(_:_:file:line:flags:) + 248
Foundation
__DataStorage.replaceBytes(in:with:length:) + 2232
Foundation
Data.InlineSlice.append(contentsOf:) + 100
Foundation
Data._Representation.append(contentsOf:) + 356
Foundation
0x1a35d2000 + 3496304
Foundation
Data.append(_:) + 148
Circle
TaskFetchOriginalImageData.dataTask(didReceiveData:response:) (TaskFetchOriginalImageData.swift:115) 
Circle
partial apply for closure #1 in closure #1 in TaskFetchOriginalImageData.loadData(urlRequest:finish:) (TaskFetchOriginalImageData.swift:77) 
Circle
thunk for @escaping @callee_guaranteed @Sendable () -> () (<compiler-generated>:0) 
libdispatch.dylib
0x1aff91000 + 407464
libdispatch.dylib
0x1aff91000 + 411520
libdispatch.dylib
0x1aff91000 + 259836
libdispatch.dylib
0x1aff91000 + 262576
libdispatch.dylib
0x1aff91000 + 302868
libsystem_pthread.dylib
_pthread_wqthread + 284

On iOS 16

Nuke version 12.1.6

Seems that the affected line is inside this func

 private func dataTask(didReceiveData chunk: Data, response: URLResponse)

of TaskFetchOriginalImageData, while appending data!

Unfortunately I am not able to replicate the crash, It happens in production few few times!

Thanks, 
Luca

**Comment by kean** [comment]
Hey, are you still able to reproduce this issue with the latest version?

**Comment by kean** [comment]
Related: https://github.com/kean/Nuke/issues/572.

Hey, @larryonoff, do you happen to have any additional information around this crash? The size of the data? The crash message? Due to how rare these crashes seem to be, I suspect it's a memory issue – hitting a hard memory limit? If it is a memory issue, I wonder if I could add some defensive code to limit the size of expected data.

**Comment by larryonoff** [comment]
@kean I have only crash from Crashlytics. See it below.

```
Crashed: com.github.kean.Nuke.ImagePipeline
0  libswiftFoundation.dylib       0xfe768 <redacted> + 344
1  libswiftFoundation.dylib       0xab68 $s10Foundation4DataV11InlineSliceV21ensureUniqueReferenceyyF + 152
2  libswiftFoundation.dylib       0x12fb0 $s10Foundation4DataV11InlineSliceV6append10contentsOfySW_tF + 36
3  libswiftFoundation.dylib       0x13d5c $s10Foundation4DataV15_RepresentationO6append10contentsOfySW_tF + 568
4  BEAT                           0x7b929c TaskFetchOriginalImageData.dataTask(didReceiveData:response:) + 115 (TaskFetchOriginalImageData.swift:115)
5  BEAT                           0x7baad8 partial apply for closure #1 in closure #1 in TaskFetchOriginalImageData.loadData(urlRequest:finish:) + 77 (TaskFetchOriginalImageData.swift:77)
6  BEAT                           0x79949c thunk for @escaping @callee_guaranteed @Sendable () -> () + 4350137500 (<compiler-generated>:4350137500)
7  libdispatch.dylib              0x63094 <redacted> + 24
8  libdispatch.dylib              0x64094 <redacted> + 16
9  libdispatch.dylib              0xa73c <redacted> + 644
10 libdispatch.dylib              0xb1f4 <redacted> + 408
11 libdispatch.dylib              0x14ec8 <redacted> + 632
12 libsystem_pthread.dylib        0x1e00 _pthread_wqthread + 284
13 libsystem_pthread.dylib        0x192c start_wqthread + 8
```

<img width="1228" alt="Screenshot 2024-04-25 at 11 41 43" src="https://github.com/kean/Nuke/assets/372616/b65905c1-ce0b-4fc0-b1ee-bd60fc03f027">

I would like to add that we had another similar issue (not with Nuke), when downloading video files incrementally. Our fix was checking the length of Data to get it contents. See the sample below.

```swift
func x() {
          let lowerBound = dataRequest.requestedOffset
          let upperBound = lowerBound + Int64(dataRequest.requestedLength)

          dataRequest.respond(with: data[safe: lowerBound..<upperBound])
}


private extension Data {
  subscript(
    safe range: Range<Int64>
  ) -> Data {
    guard !isEmpty else {
      return Data()
    }

    let safeRange = range.clamped(to: 0..<Int64(count))
    guard !safeRange.isEmpty else {
      return Data()
    }

    return self[safeRange]
  }
}
```

**Comment by choulepoka** [comment]
Not sure this has any bearing on this bug, but our crashes for this specific problem are 100% on iOS 18+, which is the minority of our users (iOS 18 = 23% of our users, vs 77% for iOS 17 and older)

Something must've changed in iOS 18 that exacerbate the problem

**Comment by chichkanov** [comment]
I am getting this crash on app start then I register a custom ImageDecoding

App init:
```
ImageDecoderRegistry.shared.register { context in
        NukeSvgDecoder.enable(context: context)
}
```

```
final class NukeSvgDecoder: ImageDecoding, Sendable {
    func decode(_ data: Data) throws -> Nuke.ImageContainer {
        guard let decoded = SDImageSVGCoder.shared.decodedImage(with: data) else {
            return .init(image: .shareLogoEyesOnly) // TODO: error
        }
        return .init(image: decoded)
    }
}
```

**Comment by larryonoff** [comment]
@kean We have a device where the crash is always reproduced.

I checked Crashlytics logs, and it seems the crash occurs due to insufficient RAM.

**Comment by larryonoff** [comment]
> Related: #572.
> 
> Hey, @larryonoff, do you happen to have any additional information around this crash? The size of the data? The crash message? Due to how rare these crashes seem to be, I suspect it's a memory issue – hitting a hard memory limit? If it is a memory issue, I wonder if I could add some defensive code to limit the size of expected data.

Loading videos into files instead of storing full videos in RAM seems like a good solution.

**Comment by larryonoff** [comment]
We migrated our video loading mechanism to a custom solution, loading video files directly to disk instead of memory. Consequently, the issue was resolved..

**Comment by kean** [comment]
> that loads video files directly to the disk instead of memory

That makes a lot of sense. I think I should do a better job communicating this limitation in the documentation. It's really only designed to replace animations that are small enough to fit in memory.

**Comment by larryonoff** [comment]
> > that loads video files directly to the disk instead of memory
> 
> That makes a lot of sense. I think I should do a better job communicating this limitation in the documentation. It's really only designed to replace animations that are small enough to fit in memory.

Maybe even some runtime warning in debug mode.

**Comment by kean** [comment]
> whether data is loaded via a data task or a file task

It is currently possible only by specifying a custom `DataLoader`. I've had an idea to ideally load images using file tasks and move the files directly to `DataCache,` but I never got to implement it.

**Comment by larryonoff** [comment]
> > whether data is loaded via a data task or a file task
> 
> It is currently possible only by specifying a custom `DataLoader`. I've had an idea to ideally load images using file tasks and move the files directly to `DataCache,` but I never got to implement it.

We had a custom `DataLoader`, it will not be of assistance since `Nuke` internally utilizes `Data` objects on completion and caching, rather than file `URL`-s.

Implementing a file task will substantially enhance the memory usage of `Nuke`.

**Comment by larryonoff** [comment]
> > Implementing a file task will substantially enhance the memory usage of Nuke.
> 
> I think there are trade-offs. For most "regular"-sized images, you want to fetch directly to memory to be able to make images ready for display as soon as possible. With files, you would still need to bring files in memory, bitmap the images, and put them into the memory cache. The only savings are during the download, and I'm not sure they are going to be substantial, but it would be definitely interesting to measure it side by side with other parameters being the same.

Indeed.

In my opinion, if Nuke intends to provide fully and completely videos support, file tasks are necessary. Currently, the memory usage of videos is unexpectedly high at certain moments, particularly as when our application displays a large number of videos in a collection view.

**Comment by jonbrooks** [comment]
I am encountering this bug in Nuke `12.1.6`, and it strangely only started happening when an unrelated ad campaign rendered by Google Ads SDK went active. I'm not sure what to make of that.  Some notes that may or may not be useful:

- As mentioned [here](https://github.com/kean/Nuke/issues/572#issuecomment-1191247948) in a related thread on this issue, it doesn't seem to be due to memory exhausting in my case.
- Assuming the debugger is accurate, I wonder if there is a race condition: I am in the `else` block where `data.isEmpty` should be `false`, but in fact it's being reported as `true`:

<img width="947" alt="Image" src="https://github.com/user-attachments/assets/8e7c967c-09ed-4cf3-bea5-a2f900718962" />

**Comment by jonbrooks** [comment]
Thanks for the suggestion. Strangely enough, memory did not seem to be the issue in my case, at least in the instance I caught in the debugger:
<img width="1328" alt="Image" src="https://github.com/user-attachments/assets/14663d7a-6e99-472e-a14d-ea285bfd5350" />

**Comment by PeterKovacs89** [comment]
I keep receiving a crash in the same line. After loading images one by one (it's a slideshow), after ~100 items my app is crashing.
I see an error log in the console:
`Foundation/Data.swift:320: Fatal error: unable to allocate memory for length (3171635)`

The strange thing is, my chunk is 0 bytes.

<img width="442" height="407" alt="Image" src="https://github.com/user-attachments/assets/dea4275c-9086-4694-806b-d5fb3c27e07e" />

**Comment by PeterKovacs89** [comment]
@choulepoka, I don't see your fork. Is it a private fork? I tried to follow your steps, but I can still reproduce the crash. Would you mind publishing your solution? At least I could verify the fix. Thank you!

**Comment by choulepoka** [comment]
@PeterKovacs89 You can take a look at my changes at https://github.com/choule99/Nuke/tree/xcode16

The changes are mostly superficial, just making it all work with xcode 16.4, and activating swift 6 upcoming feature flags
